services:
  qibot:
    build: .
    container_name: qibot
    ports:
      - "8081:8081"
    environment:
      GOOGLE_API_KEY: "your_google_api_key"
      REDIS_ADDR: redis:6379
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./leads.db:/app/leads.db
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped