#!/bin/bash

# QI Telecom Chatbot - Security Demonstration
# This script demonstrates the security features implemented

echo "🛡️  QI TELECOM CHATBOT - SECURITY DEMONSTRATION"
echo "================================================"
echo ""

echo "📋 Security Features Implemented:"
echo "  ✅ Input validation and sanitization"
echo "  ✅ Rate limiting protection" 
echo "  ✅ Security headers (CSP, XSS Protection, etc.)"
echo "  ✅ CORS with configurable origins"
echo "  ✅ Request size limits"
echo "  ✅ HTTPS enforcement (configurable)"
echo "  ✅ Session security with timeouts"
echo "  ✅ Safe logging with sanitization"
echo "  ✅ Environment validation"
echo "  ✅ Comprehensive test coverage"
echo ""

echo "🔧 Configuration Examples:"
echo ""

echo "📁 Production Environment (.env):"
echo "GOOGLE_SHEETS_ID=your_real_sheets_id"
echo "FORCE_HTTPS=true"
echo "ALLOWED_ORIGINS=https://yourdomain.com"
echo "RATE_LIMIT_RPM=30"
echo "RATE_LIMIT_BURST=5"
echo "MAX_REQUEST_SIZE_BYTES=512000"
echo "REDIS_PASSWORD=strong_password_here"
echo ""

echo "📁 Development Environment (.env):"
echo "GOOGLE_SHEETS_ID=your_test_sheets_id"
echo "FORCE_HTTPS=false"
echo "ALLOWED_ORIGINS=http://localhost:8081,https://localhost:8081"
echo "RATE_LIMIT_RPM=60"
echo "RATE_LIMIT_BURST=10"
echo ""

echo "🚀 Starting Secure Server (Demo):"
echo "# Set environment variables"
echo "export GOOGLE_SHEETS_ID=demo_sheet_id"
echo "export FORCE_HTTPS=false"
echo "export ALLOWED_ORIGINS=http://localhost:8081"
echo "export RATE_LIMIT_ENABLED=true"
echo ""
echo "# Start the server"
echo "./qibot"
echo ""

echo "🧪 Security Test Examples:"
echo ""

echo "1️⃣  Input Validation Test:"
echo "   ❌ BAD:  curl -X POST -d '{\"user_id\":\"user<script>\",\"message\":\"' OR '1'='1\"}'"
echo "   ✅ GOOD: curl -X POST -d '{\"user_id\":\"user123\",\"message\":\"Olá, preciso de ajuda\"}'"
echo ""

echo "2️⃣  Rate Limiting Test:"
echo "   ❌ BAD:  for i in {1..100}; do curl -X POST localhost:8081/chatbot & done"
echo "   ✅ GOOD: Normal usage respects rate limits"
echo ""

echo "3️⃣  CORS Test:"
echo "   ❌ BAD:  curl -H 'Origin: https://malicious-site.com' localhost:8081/chatbot"
echo "   ✅ GOOD: curl -H 'Origin: http://localhost:8081' localhost:8081/chatbot"
echo ""

echo "4️⃣  Request Size Test:"
echo "   ❌ BAD:  curl -X POST -d \"$(head -c 2M </dev/zero | tr '\\0' 'a')\" localhost:8081/chatbot"
echo "   ✅ GOOD: Normal sized requests work fine"
echo ""

echo "📊 Security Headers Verification:"
echo "curl -I http://localhost:8081/health"
echo "Expected headers:"
echo "  X-Content-Type-Options: nosniff"
echo "  X-Frame-Options: DENY"
echo "  X-XSS-Protection: 1; mode=block"
echo "  Content-Security-Policy: default-src 'self'..."
echo ""

echo "🔒 Docker Security (Production):"
echo "docker-compose up -d"
echo "- Runs as non-root user (1000:1000)"
echo "- Redis with password protection"
echo "- Read-only credential files"
echo "- Environment variable based config"
echo ""

echo "✅ Security Implementation Complete!"
echo "   The QI Telecom chatbot now has enterprise-grade security"
echo "   suitable for production deployment."
echo ""
echo "📖 For more details, see README.md"